server:
  port: 9090
spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    platform: postgres
    username: postgres
    password: root

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka/
  instance:
    hostname: localhost
